### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by dazedcrazy** [Chuchodavids/guide2go#2]
**Describe the bug**
No longer works after updating. See error below

**To Reproduce**
1. Pull from git or pull using docker-compose
2. Build from soucre or build with docker
3. Run either one, gets cache data from SD
4. Then this error

docker error
```
2023/05/08 16:53:08 [G2G  ] Create XMLTV File [/app/tv_grab_file.xmltv]

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x713838]

goroutine 1 [running]:

main.GetImageUrl(0xc0001a0c80, 0x74, 0xc00028e0e0, 0x20, 0xc0001b1bd0, 0x44)

	/app/cache.go:588 +0x2b8

main.(*cache).GetIcon(0xab6a40, 0xc004be1d80, 0xa, 0xc000992100, 0x3, 0x4)

	/app/cache.go:659 +0x643

main.getProgram(0x0, 0x0, 0x0, 0x0, 0xc0014f3cd0, 0x5, 0xc0014f3cd8, 0x8, 0xc0014f3ce0, 0x7, ...)

	/app/xmltv.go:176 +0xa15

main.CreateXMLTV(0x7ffd337e7f3f, 0x10, 0x0, 0x0)

	/app/xmltv.go:86 +0xb22

main.(*SD).Update(0xc0000ce700, 0x7ffd337e7f3f, 0x10, 0xe, 0x1)

	/app/data.go:48 +0x1c8

main.main()

	/app/main.go:47 +0x28f
```
ubuntu error
```
2023/05/08 18:05:12 [G2G  ] Create XMLTV File [tv_grab_file.xml]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x6e4f15]

goroutine 1 [running]:
main.GetImageUrl({0xc0018bf700?, 0x32?}, {0xc000360040?, 0x1?}, {0xc0031a3b30, 0x44})
        /home/komp/guide2go/cache.go:588 +0x1f5
main.(*cache).GetIcon(0x0?, {0xc0046bcf20, 0xa})
        /home/komp/guide2go/cache.go:659 +0x307
main.getProgram({{0x0, 0x0}, {0x0, 0x0}, {0xc003a4ff18, 0x6}, {0xc003a4ff30, 0xe}, {0xc003a4ff40, 0x7}, ...})
        /home/komp/guide2go/xmltv.go:176 +0x99c
main.CreateXMLTV({0x7fff731f3714?, 0x7?})
        /home/komp/guide2go/xmltv.go:86 +0xb18
main.(*SD).Update(0xc00012c700, {0x7fff731f3714, 0xb})
        /home/komp/guide2go/data.go:48 +0x1cc
main.main()
        /home/komp/guide2go/main.go:47 +0x21a
```

**Expected behavior**
To work without error

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Comment by dazedcrazy** [comment]
Nevermind I'm an idiot. Made a new config file and didn't change local/proxy image settings.
